travis:
  secure:
    BINSTAR_TOKEN: ObPs7oIinqXBve3Xd6ymIsqdYeR1BcDpMf3zvPiiVLTs+24x/nkFSjmYpKeBv4mJAsMe625d9lEaX86PCUIcVeTiqHMtxaVqMvrgYLTdpGs/AWYYXwif/UREGAIrpO2lv3qmZto7kKRXy1ZkSVR8buuD7b9uL3ZC/VRmFjtbdMTbniVfW24zvgr0voAYs1cLrALHiuROpQUaLyy9l6mzdDtudTZeJi68HQvX7PBknYiwfjT0Jvia1xvKWTehQNci2o1zpmouwRBWA7VRUSe6F+ktMwkdG09/TM/eqk9pZOP4he+MbOwYGO229CehYgA79YTa+42rmxKm8WpqeNQB29rOBaBFfP6gTS3lFv+W5Q0fmXgOUDrFk/lfdm/e2EP6PLFl8aNeGBW4zvS3oniFD/e+md7tm3h4MuTUp/eA9F2dlvykyspMbI6NGupfhgUSkZKQFYu9fRI/RnyNYqKfuysn/xrYH1xh+X3lvOv0Ouktdx4/U5d5t7ENyK3E9Wo14Fo41kRYRwZhrLc9JZ4rljihvir9a9UxbIa2voZ0xYPAdJKY1Heyu12rdHSo4Q5nlVeiNEs+NjYXgR6bw4hSfE8CTVpsdwfGzoa40NXzZfl2N8U8ic7NGTo+TydqDzd5XTXA1kQpHuLdbu+iKfxIdYfrT//xZ7U/U5pObcR2qTs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
